services:
  - type: web
    name: keymaster-api
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false  # configura este valor desde el panel de Render o render.yaml (quitar sync y poner value)
